version: '3'
services:

    dockerapi:
        privileged: true
        image: docker:stable-dind
        container_name: dockerAPI
        ports:
          - "2375:2375"
        volumes:
            - docker_vol:/var/lib/docker
            - ../../dev/daemon.json:/etc/docker/daemon.json:ro
            - ../../dev/certs/:/data/certs/
        networks:
            - husky_net

    huskyapi:
        container_name: huskyCIAPI
        build:
            context: ../
            dockerfile: dev/huskyCIAPI.Dockerfile
        command: "go run server.go"
        env_file:
            - huskyCIAPI.env
        volumes:
            - docker_vol:/var/lib/docker
            - ../../dev/certs/client-huskyapi-cert.pem:/go/src/github.com/globocom/husky/cert.pem:ro
            - ../../dev/certs/client-huskyapi-key.pem:/go/src/github.com/globocom/husky/key.pem:ro
            - ../../dev/certs/ca.pem:/go/src/github.com/globocom/husky/ca.pem:ro
        ports:
          - "8888:8888"
        networks:
            - husky_net
        depends_on:
            - mongodb
            - dockerapi
        external_links:
            - dockerapi:dockerapi

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: dev/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - husky_net
networks:
    husky_net:

volumes:
    docker_vol:
    mongo_vol:
