name: "Database integration tests"

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  mongodb-integration-test:
    name: MongoDB integration test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mongo:4.2.2
        ports:
          - "27017:27017"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run MongoDB integration test
        run: |
          make integration-test

